import { CardData } from "../types/card-data";
import { PlayfieldState } from "../types/playfield-state";
import { Ranks } from "../types/ranks";
import { Suits } from "../types/suits";

/**
 * Describes a card that qualifies for automatic collection to a foundation pile.
 */
export interface AutoCollectCandidate {
    /** The card to be moved. */
    card: CardData;
    /** Source pile type: "tableau" or "waste". */
    sourceType: "tableau" | "waste";
    /** Source pile index (0–6 for tableau; 0 for waste). */
    sourcePileIndex: number;
    /** Index of the card within its source pile. */
    sourceCardIndex: number;
    /** Index of the destination foundation pile. */
    targetFoundationIndex: number;
}

interface FoundationSummary {
    /** Index of the first empty foundation pile, or -1 when none are empty. */
    firstEmptyFoundationIndex: number;
    /** Per-suit top foundation metadata for O(1) destination checks. */
    topBySuit: Partial<Record<Suits, { index: number; rankIndex: number }>>;
    /** Lowest top-rank index among all started foundations, if any. */
    lowestStartedRankIndex: number | null;
    /** Lowest top-rank index among started red foundations, if any. */
    lowestRedRankIndex: number | null;
    /** Lowest top-rank index among started black foundations, if any. */
    lowestBlackRankIndex: number | null;
    /** Number of started red foundations. */
    redStartedCount: number;
    /** Number of started black foundations. */
    blackStartedCount: number;
}

/**
 * Build a fast rank -> index lookup table from ordered rank list.
 * @param ranks Ordered rank sequence from lowest to highest.
 * @returns Map of rank name to zero-based rank index.
 */
function buildRankIndexMap(ranks: Ranks[]): Record<string, number> {
    return Object.fromEntries(ranks.map((rank, index) => [rank, index]));
}

/**
 * Resolve the numeric index for a rank using a prebuilt lookup table.
 * @param rank Rank to resolve.
 * @param rankIndexMap Lookup generated by {@link buildRankIndexMap}.
 * @returns Zero-based rank index.
 */
function getRankIndex(rank: Ranks, rankIndexMap: Record<string, number>): number {
    return rankIndexMap[rank];
}

/**
 * Precompute foundation facts used repeatedly by auto-collect checks.
 * @param foundationPiles Current foundation piles.
 * @param rankIndexMap Rank lookup generated once per call path.
 * @param suitsToColorsMap Suit-to-color mapping.
 * @returns Aggregated foundation summary for target and safety checks.
 */
function buildFoundationSummary(
    foundationPiles: CardData[][],
    rankIndexMap: Record<string, number>,
    suitsToColorsMap: Partial<Record<Suits, string>>,
): FoundationSummary {
    const summary: FoundationSummary = {
        firstEmptyFoundationIndex: -1,
        topBySuit: {},
        lowestStartedRankIndex: null,
        lowestRedRankIndex: null,
        lowestBlackRankIndex: null,
        redStartedCount: 0,
        blackStartedCount: 0,
    };

    foundationPiles.forEach((pile, index) => {
        if (pile.length === 0) {
            if (summary.firstEmptyFoundationIndex === -1) {
                summary.firstEmptyFoundationIndex = index;
            }
            return;
        }

        const topCard = pile[pile.length - 1];
        const topRankIndex = getRankIndex(topCard.rank, rankIndexMap);
        const topColor = suitsToColorsMap[topCard.suit];

        summary.topBySuit[topCard.suit] = { index, rankIndex: topRankIndex };

        if (summary.lowestStartedRankIndex === null || topRankIndex < summary.lowestStartedRankIndex) {
            summary.lowestStartedRankIndex = topRankIndex;
        }

        if (topColor === "red") {
            summary.redStartedCount += 1;
            if (summary.lowestRedRankIndex === null || topRankIndex < summary.lowestRedRankIndex) {
                summary.lowestRedRankIndex = topRankIndex;
            }
        } else if (topColor === "black") {
            summary.blackStartedCount += 1;
            if (summary.lowestBlackRankIndex === null || topRankIndex < summary.lowestBlackRankIndex) {
                summary.lowestBlackRankIndex = topRankIndex;
            }
        }
    });

    return summary;
}

/**
 * Resolve legal foundation destination using precomputed summary.
 * @param card Candidate card.
 * @param summary Precomputed foundation summary.
 * @param rankIndexMap Rank lookup map.
 * @returns Foundation index, or -1 when no legal destination exists.
 */
function findFoundationTarget(
    card: CardData,
    summary: FoundationSummary,
    rankIndexMap: Record<string, number>,
): number {
    if (card.rank === "ace") {
        return summary.firstEmptyFoundationIndex;
    }

    const suitFoundation = summary.topBySuit[card.suit];
    if (!suitFoundation) {
        return -1;
    }

    const cardRankIndex = getRankIndex(card.rank, rankIndexMap);
    return cardRankIndex === suitFoundation.rankIndex + 1 ? suitFoundation.index : -1;
}

/**
 * Evaluate auto-collect safety using precomputed foundation summary.
 * @param card Candidate card.
 * @param summary Precomputed foundation summary.
 * @param rankIndexMap Rank lookup map.
 * @param suitsToColorsMap Suit-to-color mapping.
 * @returns True when moving card to foundation is considered safe.
 */
function isAutoCollectSafe(
    card: CardData,
    summary: FoundationSummary,
    rankIndexMap: Record<string, number>,
    suitsToColorsMap: Partial<Record<Suits, string>>,
): boolean {
    // Aces always bypass the safety rule — they are required to start foundations.
    if (card.rank === "ace") return true;

    // No foundations started yet — only aces can safely go (handled above).
    if (summary.lowestStartedRankIndex === null) return false;

    const cardRankIndex = getRankIndex(card.rank, rankIndexMap);

    // Base safety gate: card rank ≤ lowest foundation rank + 2.
    if (cardRankIndex <= summary.lowestStartedRankIndex + 2) return true;

    // Opposite-color relaxation.
    const cardColor = suitsToColorsMap[card.suit];

    if (cardColor === "red") {
        if (
            summary.blackStartedCount === 2 &&
            summary.lowestBlackRankIndex !== null &&
            cardRankIndex <= summary.lowestBlackRankIndex + 1
        ) {
            return true;
        }
    } else if (cardColor === "black") {
        if (
            summary.redStartedCount === 2 &&
            summary.lowestRedRankIndex !== null &&
            cardRankIndex <= summary.lowestRedRankIndex + 1
        ) {
            return true;
        }
    }

    return false;
}

/**
 * Validate whether a card can be placed onto a target pile according to
 * standard Solitaire rules for tableau and foundation piles.
 *
 * Tableau rules:
 *  - Empty tableau: only Kings allowed
 *  - Non-empty tableau: card rank must be exactly 1 below top card,
 *    and suit color must differ (red vs black)
 *
 * Foundation rules:
 *  - Empty foundation: only Aces allowed
 *  - Non-empty foundation: card rank must be exactly 1 above top card,
 *    and card suit must match top card suit
 *  - Card must currently be the top card in its source pile
 *
 * @param card The card to validate.
 * @param targetTopCard The current top card of the target pile, or undefined if empty.
 * @param targetPileType The type of target pile: "tableau" or "foundation".
 * @param playfieldState Current playfield state (needed only for foundation validation).
 * @param ranks Ordered rank list from lowest ("ace") to highest ("king").
 * @param suitsToColorsMap Maps each suit name to "black" or "red".
 * @returns True when the move is legal.
 */
export function isValidMove(
    card: CardData,
    targetTopCard: CardData | undefined,
    targetPileType: string,
    playfieldState: PlayfieldState,
    ranks: Ranks[],
    suitsToColorsMap: Partial<Record<Suits, string>>
): boolean {
    if (!targetTopCard && !card) {
        return false;
    }

    const targetRankIndex = targetTopCard ? ranks.indexOf(targetTopCard.rank) : -1;
    const cardRankIndex = ranks.indexOf(card.rank);

    if (targetPileType === "tableau") {
        // Empty tableau: only Kings allowed
        if (!targetTopCard && card.rank === "king") {
            return true;
        }

        // Non-empty tableau: rank must be 1 below top, colors must differ
        if (
            targetTopCard &&
            suitsToColorsMap[targetTopCard.suit] !== suitsToColorsMap[card.suit] &&
            cardRankIndex + 1 === targetRankIndex
        ) {
            return true;
        }
    } else if (targetPileType === "foundation") {
        // Validate that the card is the top card in its source pile
        const cardIndex = card.cardIndex as number;
        const pileIndex = card.pileIndex as number;
        const pileType = card.pileType as keyof PlayfieldState;

        let pileLength: number;
        if (pileType === "waste" || pileType === "draw") {
            // Waste and draw are direct arrays
            pileLength = (playfieldState[pileType] as CardData[]).length;
        } else {
            // Tableau and foundation are arrays of arrays
            pileLength = (playfieldState[pileType] as CardData[][])[pileIndex].length;
        }

        if (pileLength - 1 !== cardIndex) {
            return false;
        }

        // Empty foundation: only Aces allowed
        if (!targetTopCard && card.rank === "ace") {
            return true;
        }

        // Non-empty foundation: rank must be 1 above top, suit must match
        if (
            targetTopCard &&
            targetTopCard.suit === card.suit &&
            cardRankIndex - 1 === targetRankIndex
        ) {
            return true;
        }
    }

    return false;
}

/**
 * Find the next card that should be auto-collected to a foundation pile.
 *
 * Scan order (per spec):
 *  1. Tableau columns from left to right — only the current top face-up card
 *     of each column is considered.
 *  2. Waste top card, if no tableau candidate qualifies.
 *
 * A candidate must be both foundation-legal ({@link findFoundationTarget}) and
 * safety-approved ({@link isAutoCollectSafe}).
 *
 * @param playfield Current playfield state.
 * @param ranks Ordered rank list from lowest to highest.
 * @param suitsToColorsMap Maps each suit name to "black" or "red".
 * @returns The first valid auto-collect candidate, or null if none is found.
 */
export function findAutoCollectCandidate(playfield: PlayfieldState, ranks: Ranks[], suitsToColorsMap: Partial<Record<Suits, string>>): AutoCollectCandidate | null {
    const rankIndexMap = buildRankIndexMap(ranks);
    const foundationPiles = playfield.foundation as CardData[][];
    const foundationSummary = buildFoundationSummary(foundationPiles, rankIndexMap, suitsToColorsMap);

    // 1. Scan tableau columns from left to right.
    const tableauPiles = playfield.tableau as CardData[][];
    for (let i = 0; i < tableauPiles.length; i++) {
        const pile = tableauPiles[i];
        if (!pile.length) continue;

        const topCard = pile[pile.length - 1];
        // Only face-up top cards are eligible.
        if (topCard.face !== "up") continue;

        const targetFoundationIndex = findFoundationTarget(topCard, foundationSummary, rankIndexMap);
        if (targetFoundationIndex === -1) continue;

        if (isAutoCollectSafe(topCard, foundationSummary, rankIndexMap, suitsToColorsMap)) {
            return {
                card: topCard,
                sourceType: "tableau",
                sourcePileIndex: i,
                sourceCardIndex: pile.length - 1,
                targetFoundationIndex,
            };
        }
    }

    // 2. Check the waste top card if no tableau candidate qualified.
    const waste = playfield.waste as CardData[];
    if (waste.length > 0) {
        const topCard = waste[waste.length - 1];
        if (topCard.face === "up") {
            const targetFoundationIndex = findFoundationTarget(topCard, foundationSummary, rankIndexMap);
            if (
                targetFoundationIndex !== -1 &&
                isAutoCollectSafe(topCard, foundationSummary, rankIndexMap, suitsToColorsMap)
            ) {
                return {
                    card: topCard,
                    sourceType: "waste",
                    sourcePileIndex: 0,
                    sourceCardIndex: waste.length - 1,
                    targetFoundationIndex,
                };
            }
        }
    }

    return null;
}
